model:
  bert_model: "checkpoints/bert-uncased"
  vit_model: "models/eva_vit_g.pth"
  llm_model: "checkpoints/flan-t5-xl"
  ram_model: "models/ram_swin_large_14m.pth"

  visual_input: "ALL"
  enable_semantic_tags: True

  load_pretrained: True
  pretrained: "checkpoints/LION-FlanT5-XL/LION-FlanT5-XL.pth"
